version: '3'

services:
  web:
    restart: always
    build: .
    volumes:
       - .:/code
    links:
       - redis:redis
    expose:
       - 8000
    user: 1001:1002 ## needed for linux
    working_dir: /code/mysite
    command: python manage.py runserver 0.0.0.0:8000
    # command: daphne -b 0.0.0.0 -p 8000 mysite.asgi:application

  nginx:
   restart: always
   build: ./nginx/
   depends_on:
      - web
   ports:
      - 80:80
   links:
      - web:web

  redis:
   image: redis:latest
   expose:
      - 6379

  